#!/usr/bin/env bash
# Regenerate skills/<name>/companion-rules/ from the canonical rules/ so each skill folder is
# self-sufficient. The mapping below is the single source of truth (mirrored in each skill README).
# Run after editing any rule. CI runs it with --check to fail on drift.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHECK=0; [ "${1:-}" = "--check" ] && CHECK=1

# skill => space-separated rule basenames (no .mdc)
companions() {
  case "$1" in
    aws-deploy-and-verify)              echo "cloud-first-verification cicd-first implementation-workflow" ;;
    aws-serverless-project-bootstrap)   echo "cicd-first terraform-infra static-analysis-and-logging local-environment-hygiene" ;;
    debugging-with-evidence-ledger)     echo "systematic-debugging parallel-delegation" ;;
    e2e-flake-triage)                   echo "testing-standards testing-quality systematic-debugging" ;;
    phase-retrospective)                echo "continuous-improvement" ;;
    continuous-improvement-retrospective) echo "continuous-improvement" ;;
    *) echo "" ;;
  esac
}

drift=0
for d in "$HERE"/skills/*/ "$HERE"/user-level/skills/*/; do
  n="$(basename "$d")"; want="$(companions "$n")"
  [ -n "$want" ] || { echo "no companion mapping for $n" >&2; drift=1; continue; }
  cd="$d/companion-rules"
  if [ "$CHECK" -eq 1 ]; then
    for r in $want; do
      if ! cmp -s "$HERE/rules/$r.mdc" "$cd/$r.mdc" 2>/dev/null; then echo "DRIFT: $n/companion-rules/$r.mdc"; drift=1; fi
    done
    for f in "$cd"/*.mdc; do [ -e "$f" ] || continue; b="$(basename "$f" .mdc)"
      case " $want " in *" $b "*) ;; *) echo "STALE: $n/companion-rules/$b.mdc"; drift=1 ;; esac; done
  else
    rm -rf "$cd"; mkdir -p "$cd"
    for r in $want; do cp "$HERE/rules/$r.mdc" "$cd/$r.mdc"; done
    { echo "# Companion rules for \`$n\`"; echo
      echo "Copies of the rules this skill assumes are loaded. Canonical versions: \`/rules/\`."
      echo "Regenerated by \`scripts/sync-companions.sh\` — do not edit here."; echo
      for r in $want; do echo "- \`$r.mdc\`"; done
      echo; echo "Install: \`cp companion-rules/*.mdc <your-repo>/.cursor/rules/\`"; } > "$cd/README.md"
    echo "synced: $n ← $want"
  fi
done
if [ "$CHECK" -eq 1 ]; then [ "$drift" -eq 0 ] && echo "companion rules in sync" || exit 1; fi
